language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install codecov
script: make test
deploy:
  provider: heroku
  api_key:
    secure: PDZmm3K+40Rw8iDsJ8JagD/robkH4OOkAv8I2L/fe26Av+5ujytvBY4aDYb6mCMOBI9fbDXVkjrRCO/Ua2rNQ0TQFQdUKVGnE9Qt2qJ3xiba3CS/3G42CZJ9f42eVN4mF+pI1cuTP+78pO+DNfigZmomIDRQJR1345ezDH9rQZVvlr6qoxHfWLjHMPKNyu/DUFnrpRonXV8UX4zWBl02V2Z9gztLFcNwoZeQFii3skl3829iiejHkyOJSAjQ5nCa7o0We3zz0zvZ8/vsViDxtZtJcz2bntTO+75O8LHAi84LkY8EPgO6K4s/k+FNWbRHmFHRNOx6c+3QTHBt0buTbXTTWqw64qkvQrBQebEI1vqQwGUz3+JHQGcVwyUCun2A0GYOsL0yvPOyXNyuUcLZqzOB/whDyXME8Hexy0BILL+kcFbPD2W9K3HLQXM2LEE8lUu1i4Gh47Fe3C0kUCkTxH9+ypBFRnett9HskrjGVD/SbcSnLuMWHkWziG6XEPu5NDahOFfGNxFFp57JzpSsehF8DzRZ1XwRVhMX+mVLH+V+HIGFOnhKT9kTaCSljpoi5bQ4i0fGUnFKAridFIpO8nze1MtIDtZCc8Qf2IspAibyujGQ2Kh8fA8My6IvRL/kFzks3dz0cRY2+3zAzjooaNBqEqfl58tb/n+qKgO5o30=
  app: webfram

branches:
  only:
  - master
notifications:
  email: false
